### ISSUE TITLE
小哥 AS用gradle引入后 运行时报错 崩溃 只写了布局xml

### ISSUE THREAD

**Issue by maobon** [kingideayou/SlideBottomPanel#6]
11-18 17:05:57.704 3268-3268/com.bob.demo.bobdemo E/InputEventReceiver: Exception dispatching input event.
11-18 17:05:57.704 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI: java.lang.NullPointerException
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at me.next.slidebottompanel.SlideBottomPanel.displayPanel(SlideBottomPanel.java:335)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at me.next.slidebottompanel.SlideBottomPanel.handleActionUp(SlideBottomPanel.java:191)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at me.next.slidebottompanel.SlideBottomPanel.dispatchTouchEvent(SlideBottomPanel.java:166)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1959)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1411)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1907)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.View.dispatchPointerEvent(View.java:7426)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3262)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3207)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4334)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4313)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4405)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.os.MessageQueue.nativePollOnce(Native Method)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.os.MessageQueue.next(MessageQueue.java:125)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.os.Looper.loop(Looper.java:124)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at android.app.ActivityThread.main(ActivityThread.java:5074)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at java.lang.reflect.Method.invokeNative(Native Method)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at java.lang.reflect.Method.invoke(Method.java:511)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo E/MessageQueue-JNI:     at dalvik.system.NativeStart.main(Native Method)
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo D/AndroidRuntime: Shutting down VM
11-18 17:05:57.714 3268-3268/com.bob.demo.bobdemo W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x414ecac8)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime: FATAL EXCEPTION: main
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime: java.lang.NullPointerException
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at me.next.slidebottompanel.SlideBottomPanel.displayPanel(SlideBottomPanel.java:335)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at me.next.slidebottompanel.SlideBottomPanel.handleActionUp(SlideBottomPanel.java:191)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at me.next.slidebottompanel.SlideBottomPanel.dispatchTouchEvent(SlideBottomPanel.java:166)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1959)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1411)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1907)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.View.dispatchPointerEvent(View.java:7426)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3262)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3207)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4334)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4313)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4405)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.os.MessageQueue.nativePollOnce(Native Method)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.os.MessageQueue.next(MessageQueue.java:125)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:124)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5074)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
11-18 17:05:57.724 3268-3268/com.bob.demo.bobdemo E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

向上面一滑动就崩溃了

**Comment by kingideayou** [comment]
先运行 Demo ，看一下 Demo 的代码再试一下呢？
